export const AUTHENTICATE_USER = '[auth] AUTHENTICATE_USER';
export const AUTHENTICATION_STARTED = '[auth] AUTHENTICATION_STARTED';
export const AUTHENTICATION_FINISHED = '[auth] AUTHENTICATION_FINISHED';
export const LOGOUT_USER = '[auth] LOGOUT_USER';
